### ISSUE TITLE
Sending event "Updated Shopify Customer" in an infinite loop

### ISSUE THREAD

**Issue by ParthGandhi** [PostHog/posthog-shopify-sync-plugin#1]
On a fresh install of the app on a cloud posthog instance it runs into an infinite loop where it just updates the same customers over and over again.

<img width="1148" alt="Screenshot 2022-05-31 at 6 42 57 PM" src="https://user-images.githubusercontent.com/819237/171182375-7c9c65d1-deb3-4ad4-b5c1-bd21f54a39d1.png">

**Comment by marcushyett-ph** [comment]
@sreeo was wondeirng if you might be able to help us debug this issue a bit?

**Comment by marcushyett-ph** [comment]
Looking at the code it might make sense to stop doing updates all together and do this instead:
https://github.com/PostHog/posthog-shopify-sync-plugin/blob/ed801acdd860c4faf1e0c78115e8a1a5d01baac0/index.js#L86-L93


```javascript
if (customerEmail !== undefined && !customerRecordExists) {
    // to update a user, shouldn't we send properties in $set? 
    posthog.capture('Created Shopify Customer', {
        distinct_id: order.customer.email,
        $set : {
            ...order.customer
        }
    })
}
```
